name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Yotta.SoloGrit.SmsSender 
    - name: Build
      run: dotnet build Yotta.SoloGrit.SmsSender --no-restore
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Yotta.SoloGrit.SmsSender/Yotta.SoloGrit.SmsSender/Yotta.SoloGrit.SmsSender.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
